= Object Copier

== FAQ
* What will happen if both side annotated?
* DTO is annotated but not Entity so what will happen when copy Entity to DTO?

== Interface ProcessCustomCopy<S, D>
If we need any custom processing during the copy object then we can use this interface. It will work like below ways:

* Will call only once if we Implement it.
* It can call for each field during copy process. Just using customProcess =  true from annotation.

=== ProcessCustomCopy<S, D> Methods description
* *meAsSrc(S source, D destination, String fieldName):* If enable for field then it will call one time when the field will copy and implementation placed as Source.
* *meAsDst(D source, S destination, String fieldName):* If enable for field then it will call one time when the field will copy and implementation placed as Destination.
* *meAsSrc(S source, D destination):* Will call once when implementation placed as Source.
* *meAsDst(D source, S destination):* Will call once when implementation placed as Destination.

== Copy Object

* Available Annotation
** DataMappingInfo
*** name (Default: anonymous): It will use for excel sheet name or use as a csv file name.
*** isStrict (Default: false): If isStrict true then copier will not copy if the dataMapping annotation not present or source not available.

** DataMapping
*** source (required): where to copy value and initialize annotated property using that value.
*** customProcess (true/false) Default: false: will call the custom processor if custom processor implemented.
*** name (Default: null): It will use for export and import value to serializable content such as csv, excel etc.


== Export Import
* If the Object is Nested then it will show like Address >> Id it's mean suppose to Person has an Object called Address
inside of it.
* Import will also parse the Address >> Id according to object.


== Copy Process
* Parse Annotation Information
* Make Source Destination List
* Perform Source Field to Destination Copy
** If custom call then field will not copy call the custom Processor
** If field is not primitive then process individually
* Finally Call the custom method once.
* Note
** If source & destination both have mapping annotation then always destination mapping will get priority.
** If source & destination will no mapping annotation then copy match property according to destination class.
** If source & destination anyone has mapping then thai will consider as mapping.
** If DataMappingInfo isStrict = true then nothing will copy if there is no mapping annotation.
* Copy Criteria
** Entity Object to DTO Class
** Entity Object to DTO Object
** DTO Object to Entity Class
** DTO Object to Entity Object


* Copy Entity to DTO
* Copy DTO to Entity
* Export to CSV
* Import from CSV
* Export to Excel
* Import from Excel
* Object Validation
** Source
** Destination


* DataMapping annotation inputs
** source: Source Field name
** sourceAlias: Basically use for csv/excel read write, absence of Source field name
** SourceOrder: If Source and SourceAlias not available for csv/excel then we can specify SourceOrder by put number
** IsCustomCall: It will allow to call the custom method for custom things

* Copy Process
** Scan Annotation
*** If found ObjectMap annotation in destination then skip source scan
*** If not found Destination annotation then scan source and active it
*** If there is no annotation then map the object according match name and type

* Custom Call back

* Problems
** How to export/import Object Class from/to csv/excel?





EntityBasic == CopyTo
DtoBasic == Value


EntityBasic == Value
DtoBasic == CopyTo
